PATH:
  root_dir: /Users/zfwang/machinelearning/deeplearning_project/computer_vision/image_classification/mnist  # 项目根目录
  data_dir: /Users/zfwang/machinelearning/datasets/mnist/  # 本地数据根目录
  # 在线数据
  data_url_base: http://yann.lecun.com/exdb/mnist/  # 在线下载数据根目录
  data_path_base: /Users/zfwang/machinelearning/datasets/mnist/mnist_gz/  # 在线数据下载到本地路径
  data_url_base_key_file:                            # 在线下载数据根目录
    train_data: train-images-idx3-ubyte.gz
    train_label: train-labels-idx1-ubyte.gz
    test_data: t10k-images-idx3-ubyte.gz
    test_label: t10k-labels-idx1-ubyte.gz
  # 本地数据
  data_path_base2: /Users/zfwang/machinelearning/datasets/mnist/MNISTImages/
  data_path_base_folder_names2:
    - class_a
    - class_b
    - class_c
  # 本地模型
  model_path: /Users/zfwang/machinelearning/deeplearning_project/computer_vision/image_classification/mnist/models/mnist.h5
  model_image_path: /Users/zfwang/machinelearning/deeplearning_project/computer_vision/image_classification/mnist/models_images/model.png
DATA:
  validation_split: 0.2
  buffer_size: 
  num_classes: 10
IMAGE:
  image_size:
    width: 28
    height: 28
  flatten_image_size: 784
MODEL:
  epochs: 12
  batch_size: 128
  learning_rate: 1e-3
